### ISSUE TITLE
use full URI in HTTP Header or add to IANA link relations registry

### ISSUE THREAD

**Issue by elf-pavlik** [converspace/webmention#38]
[IANA link relations registry](http://www.iana.org/assignments/link-relations/link-relations.xhtml) does NOT include *webmention* and following RFC5988 this rel should use full URI

>Note that extension relation types are REQUIRED to be absolute URIs
   in Link headers, and MUST be quoted if they contain a semicolon (";")
   or comma (",") (as these characters are used as delimiters in the
   header itself).

https://tools.ietf.org/html/rfc5988#section-5.3

I just added similar issue to http://indiewebcamp.com/micropub#HTTP_Header

**Comment by aaronpk** [comment]
Full URI is not required, see the discussion in aaronpk/Micropub#1
